saml:
  entity-id: ${IAM_SAML_ENTITY_ID:urn:iam:iam-devel}
  keystore: ${IAM_SAML_KEYSTORE:classpath:/saml/samlKeystore.jks}
  keystore-password: ${IAM_SAML_KEYSTORE_PASSWORD:password}
  key-id: ${IAM_SAML_KEY_ID:iam}
  key-password: ${IAM_SAML_KEY_PASSWORD:password}
  idp-metadata: ${IAM_SAML_IDP_METADATA:classpath:/saml/idp-metadata.xml}
  max-assertion-time-sec: ${IAM_SAML_MAX_ASSERTION_TIME:3000}
  max-authentication-age-sec: ${IAM_SAML_MAX_AUTHENTICATION_AGE:86400}