security:
  filter-order: 1

server:
  port: ${IAM_PORT:8080}
  tomcat:
    accesslog:
      enabled: true
      directory: /tmp
      pattern: "%a asdasd"

  use-forward-headers: ${IAM_USE_FORWARDED_HEADERS:false}

spring:
  profiles:
    active: h2-test,registration

  application:
    name: INDIGO IAM
    
  jpa:
    generate-ddl: true

  mail:
    host: ${IAM_MAIL_HOST:localhost}
    port: ${IAM_MAIL_PORT:25}
    username: ${IAM_MAIL_USERNAME:}
    password: ${IAM_MAIL_PASSWORD:}

  velocity:
    enabled: false

iam:
  host: ${IAM_HOST:localhost}
  baseUrl: ${IAM_BASE_URL:http://${iam.host}:8080}
  issuer: ${IAM_ISSUER:http://${iam.host}:8080}

  token:
    # This is the registration access token lifetime
    lifetime: ${IAM_REGISTRATION_TOKEN_LIFETIME:-1}  

  organisation:
    name: ${IAM_ORGANISATION_NAME:indigo-dc}

  keyStoreLocation: ${IAM_KEY_STORE_LOCATION:classpath:keystore.jwks}

x509:
  trustAnchorsDir: ${IAM_X509_TRUST_ANCHORS_DIR:/etc/grid-security/certificates}
  trustAnchorsRefreshMsec: ${IAM_X509_TRUST_ANCHORS_REFRESH:14400}

google:
    issuer: https://accounts.google.com

    client:
      clientId: ${IAM_GOOGLE_CLIENT_ID:define_me_please}
      clientSecret: ${IAM_GOOGLE_CLIENT_SECRET:define_me_please}
      redirectUris: ${IAM_GOOGLE_CLIENT_REDIRECT_URIS:${iam.baseUrl}/openid_connect_login}
      scope: openid,profile,email,address,phone

github:
  client:
    clientId: ${IAM_GITHUB_CLIENT_ID:define_me_please}
    clientSecret: ${IAM_GITHUB_CLIENT_SECRET:define_me_please}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    preEstablishedRedirectUri: http://${iam.baseUrl}/gh_login
    useCurrentUri: false
    scope: user:email
  resource:
    userInfoUri: https://api.github.com/user
    
notification:
  disable: ${IAM_NOTIFICATION_DISABLE:false}
  mailFrom: ${IAM_NOTIFICATION_FROM:indigo@localhost}
  taskDelay: ${IAM_NOTIFICATION_TASK_DELAY:5000}
  cleanupAge: ${IAM_NOTIFICATION_CLEANUP_AGE:30}
  adminAddress: ${IAM_NOTIFICATION_ADMIN_ADDRESS:indigo-alerts@localhost}
  subject:
    confirmation: Confirm Indigo registration request
    activated: Indigo Account activated
    rejected: Indigo Account request rejected
    adminHandleRequest: New Indigo account request
    resetPassword: Indigo account reset password

task:
  tokenCleanupPeriodMsec: ${IAM_TOKEN_CLEANUP_PERIOD_MSEC:300000}
  approvalCleanupPeriodMsec: ${IAM_APPROVAL_CLEANUP_PERIOD_MSEC:300000}