#
# Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2016-2018
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

security:
  filter-order: 1

server:
  port: ${IAM_PORT:8080}
  tomcat:
    accesslog:
      enabled: ${IAM_TOMCAT_ACCESS_LOG_ENABLED:false}
      directory: ${IAM_TOMCAT_ACCESS_LOG_DIRECTORY:/tmp}
      pattern: "%{X-Forwarded-For}i %l %u %t \"%r\" %s %b"

  use-forward-headers: ${IAM_USE_FORWARDED_HEADERS:false}

spring:
  profiles:
    active: h2-test

  application:
    name: INDIGO IAM
    
  jpa:
    generate-ddl: true

  mail:
    host: ${IAM_MAIL_HOST:localhost}
    port: ${IAM_MAIL_PORT:25}
    username: ${IAM_MAIL_USERNAME:}
    password: ${IAM_MAIL_PASSWORD:}

  velocity:
    enabled: false

iam:
  host: ${IAM_HOST:localhost}
  baseUrl: ${IAM_BASE_URL:http://${iam.host}:8080}
  issuer: ${IAM_ISSUER:http://${iam.host}:8080}
  logoImageUrl: ${IAM_LOGO_URL:resources/images/indigo-logo.png}
  topbarTitle: ${IAM_TOPBAR_TITLE:INDIGO IAM for ${iam.organisation.name}}

  token:
    # This is the registration access token lifetime
    lifetime: ${IAM_REGISTRATION_TOKEN_LIFETIME:-1}  

  organisation:
    name: ${IAM_ORGANISATION_NAME:indigo-dc}

  keyStoreLocation: ${IAM_KEY_STORE_LOCATION:classpath:keystore.jwks}
  
  privacyPolicy:
    url: ${IAM_PRIVACY_POLICY_URL:}
    text: ${IAM_PRIVACY_POLICY_TEXT:Privacy policy}
  
  loginButton:
    text: ${IAM_LOGIN_BUTTON_TEXT:Sign in}

  enableScopeAuthz: ${IAM_ENABLE_SCOPE_AUTHZ:true}

  access_token:
    include_authn_info: ${IAM_ACCESS_TOKEN_INCLUDE_AUTHN_INFO:false}

x509:
  trustAnchorsDir: ${IAM_X509_TRUST_ANCHORS_DIR:/etc/grid-security/certificates}
  trustAnchorsRefreshMsec: ${IAM_X509_TRUST_ANCHORS_REFRESH:14400}

oidc:
  providers:
  - name: google
    issuer: https://accounts.google.com
    client:
      clientId: ${IAM_GOOGLE_CLIENT_ID:define_me_please}
      clientSecret: ${IAM_GOOGLE_CLIENT_SECRET:define_me_please}
      redirectUris: ${IAM_GOOGLE_CLIENT_REDIRECT_URIS:${iam.baseUrl}/openid_connect_login}
      scope: openid,profile,email,address,phone
    loginButton:
      order: 0
      text: Sign-in with Google
      style: google

github:
  client:
    clientId: ${IAM_GITHUB_CLIENT_ID:define_me_please}
    clientSecret: ${IAM_GITHUB_CLIENT_SECRET:define_me_please}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    preEstablishedRedirectUri: http://${iam.baseUrl}/gh_login
    useCurrentUri: false
    scope: user:email
  resource:
    userInfoUri: https://api.github.com/user
    
notification:
  disable: ${IAM_NOTIFICATION_DISABLE:false}
  mailFrom: ${IAM_NOTIFICATION_FROM:indigo@localhost}
  taskDelay: ${IAM_NOTIFICATION_TASK_DELAY:5000}
  cleanupAge: ${IAM_NOTIFICATION_CLEANUP_AGE:30}
  adminAddress: ${IAM_NOTIFICATION_ADMIN_ADDRESS:indigo-alerts@localhost}
  subject:
    confirmation: Confirm your ${iam.organisation.name} registration request
    activated: Your ${iam.organisation.name} account is now active
    rejected: Your request for a ${iam.organisation.name} account has been rejected
    adminHandleRequest: New ${iam.organisation.name} account request
    resetPassword: Reset your ${iam.organisation.name} account password

task:
  tokenCleanupPeriodMsec: ${IAM_TOKEN_CLEANUP_PERIOD_MSEC:300000}
  approvalCleanupPeriodMsec: ${IAM_APPROVAL_CLEANUP_PERIOD_MSEC:300000}
  deviceCodeCleanupPeriodMsec: ${IAM_DEVICE_CODE_CLEANUP_PERIOD_MSEC:300000}

health:
  externalServiceProbe:
    enabled: ${IAM_HEALTH_EXTERNAL_SERVICE_PROBE_ENABLED:true}
    endpoint: ${IAM_HEALTH_EXTERNAL_SERVICE_PROBE_ENDPOINT:http://www.google.it}
    timeout: ${IAM_HEALTH_EXTERNAL_SERVICE_PROBE_TIMEOUT:5000}
    path: /health/external
  mailProbe:
    enabled: ${IAM_HEALTH_MAIL_PROBE_ENABLED:true}
    path: /health/mail
    
accountLinking:
  disable: ${IAM_ACCOUNT_LINKING_DISABLE:false}
