spring:
  profiles:
    include: mysql,google,registration,saml
    
  mail:
    host: localhost
    port: 10125

flyway:
  locations:
    - classpath:db/migration/mysql
    - classpath:db/migration/test

management:
  health:
    mail:
      enabled: false