spring:
  profiles:
    include: google,saml
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:iam;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  mail:
    host: localhost
    port: 10125

flyway:
  locations:
    - classpath:db/migration/h2
    - classpath:db/migration/test

management:
  health:
    mail:
      enabled: false
