spring:
  mvc:
    view:
      suffix: .html

server:
  context-path: /iam-test-pr
  port: ${IAM_PR_PORT:9091}
  use-forward-headers: ${IAM_PR_USE_FORWARD_HEADERS:false}

iam:
  client-id: ${IAM_PR_CLIENT_ID:tasks-app}
  client-secret: ${IAM_PR_CLIENT_SECRET:secret}
  token-info-uri: ${IAM_PR_TOKENINFO_URI:http://localhost:8080/introspect}